name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TOOLCHAIN: nightly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Pull website
      - name: Build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: dist-${{ hashFiles('./src') }}-${{ hashFiles('./assets') }}

      # Install cargo deps
      - name: Trunk build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          rustup update $TOOLCHAIN
          rustup default $TOOLCHAIN
          cargo install trunk
          cargo build --verbose
          trunk build

      # Deploy, GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
